apiVersion: v1
kind: Pod
metadata:
  name: backend-pod
  labels:
    component: backend
spec:
  containers:
    - image: matusdubrava/pyback
      name: backend
      ports:
        - containerPort: 5000
      imagePullPolicy: Never
